config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :tokens, only: [:create]
  resources :products do
    resources :reviews
  end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/all_products" => "products#all"
  post 'products/search' => 'products#search', as: 'search_products'
  # post 'tokens' => "tokens#create"
  get '/chat' => 'chats#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  before_save(:titleize_product)

  validates :name, presence: true
  validates :country_of_origin, presence: true
  validates :cost, presence: true

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}

  scope :murica, -> { where(country_of_origin: "USA") }

  scope :most_reviews, -> {(
  select("products.id, products.name, products.cost, count(reviews.id) as reviews_count")
  .joins(:reviews)
  .group("products.id")
  .order("reviews_count DESC")
  .limit(1)
  )}


  private
  def titleize_product
    self.name = self.name.titleize
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, presence: true
  validates :content_body, presence: true, length: { in: 50..250 }
  validates :rating, presence: true, length: { in: 1..5 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
before_action :authenticate_user!

def show
  render :index
end

end

app/controllers/products_controller.rb
require 'pry'

class ProductsController < ApplicationController

 before_action :authenticate_user!, except: :index

  def index
    @american_made = Product.murica
    @top = Product.three_most_recent
    @most_reviewed = Product.most_reviews
    render :index
  end

  def all
    @products = Product.all
    render :all
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product added to database"
      redirect_to all_products_path
    else
      render :all
    end
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product= Product.find(params[:id])
    @product.save
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
    end
  end

  def search
    @q = "%#{params[:query].capitalize}%"
    @products = Product.where("name LIKE ?", @q)
    render :all
  end

  def chat
    
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :authenticate_user!

  def index
    @product = Product.find(params[:product_id])
    @reviews = Review.all
    render :index
  end

  def new
    @product = Product.find(params[:product_id])
      @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save!
      flash[:notice] = "Review added to database"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review= Review.find(params[:id])
    @review.save
    if @review.update(review_params)
      redirect_to product_reviews_path(@product)
    else
      render :edit
    end
  end

  def destroy
    def destroy
      @product = Product.find(params[:id])
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to product_reviews_path(@product)
    end
  end

  private
  def review_params
    params.require(:review).permit(:author, :rating, :content_body)
  end


end

app/controllers/tokens_controller.rb
require 'pry'
require 'twilio-ruby'
class TokensController < ApplicationController
  before_action :authenticate_user!

  def create
    # Define User Identity
    identity = current_user.username

    # Create Grant for Access Token
    grant = Twilio::JWT::AccessToken::ChatGrant.new
    grant.service_sid = ENV['TWILIO_CHAT_SERVICE_SID']
    # Create an Access Token
    token = Twilio::JWT::AccessToken.new(
      ENV['TWILIO_ACCOUNT_SID'],
      ENV['TWILIO_API_KEY'],
      ENV['TWILIO_API_SECRET'],
      [grant],
      identity: identity
    )

    # Generate the token and send to client
    render json: { identity: identity, token: token.to_jwt }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/chats/index.html.erb
<h1>Live Chat</h1>
<p>Our customer service reps will help you with what you need!</p>
<%= image_tag("customer-service.jpg", :alt => "man standing at counter") %>
<div class="chat">
  <div class="messages">
    <div class="message">
      <span class="user">Mario:</span> How can we help you?
    </div>
  </div>
  <form>
    <label for="message">Message:</label>
    <input type="text" id="message" placeholder="Enter your message..." />
    <button type="submit">Send</button>
  </form>
</div>

app/views/layouts/_alerts.html.erb
<%= flash[:alert] %>
<%= flash[:notice] %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=<%= root_path %>>Mario's</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <nav class="navbar navbar-light bg-light">
      <%= form_tag search_products_path do %>
        <input class="form-control mr-sm-2" id= "searchbar" type="text" name="query" placeholder="Search our produce" autocomplete = "off">
      <% end %>
      <ul>
        <li class="nav-item">
          <a class="nav-link" href="/chat?">Live Chat</a>
        </li>
    </ul>
    </nav>

    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username.titleize %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Account", edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Sign Out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Create Account", new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class:'nav-link'%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_products_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <div class="field">
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cost %> <br>
    <%= f.text_field :cost %>
  </div>

  <div class="field">
    <%= f.label :country_of_origin %> <br>
    <%= f.text_field :country_of_origin %>
  </div>
  <div class="actions">
    <%= f.submit "Create Product" %>
  </div>
<% end %>

app/views/layouts/_reviews_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marios Speciality Foods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js' %>
    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/chat/v3.0/twilio-chat.min.js' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
        <%= render 'layouts/alerts' %>
        <%= yield %>
    </div>

  </body>
</html>

app/views/products/all.html.erb
<h2>Inventory</h2>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

<p><%= link_to "Add new product", new_product_path %></p>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= render "layouts/products_form" %>

app/views/products/index.html.erb
<h1>Mario's Speciality Foods</h1>

<%= image_tag("night-market.jpg", :alt => "night market") %>
<h3> Most Reviewed Product</h3>
<ul>
<% @most_reviewed.each do |t| %>
  <li> <%= link_to t.name, product_path(t) %></li>
  <% end %>
</ul>

<h3> New Products </h3>
<ul>
<% @top.each do |t| %>
  <li> <%= link_to t.name, product_path(t)%> </li>
<% end %>
</ul>

<h3> American Made Products </h3>
<ul>
  <% if @american_made.any? %>
    <% @american_made.each do |a| %>
      <li> <%= link_to a.name, product_path(a)%> </li>
    <% end %>
  <% else %>
    <p>There are no American made products yet</p>
  <% end %>
</ul>

<p><%= link_to "Add new product", new_product_path %></p>
<p><%= link_to "View all Products", all_products_path %></p>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/products_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h2><%= @product.cost %></h2>
<h3><%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
  <h4>Product Reviews:</h4>
  <% @product.reviews.each do |review| %>
  <ul>
    <li>
      <p> <%= review.rating %> out of 5 stars </p>
      <%= review.content_body %> -<%= review.author %> <br>
    </li>
  </ul>
  <% end %>
  <% else %>
    <p>There are no reviews for this product yet</p>
  <% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<p><%= link_to "Edit", edit_product_path(@product)%></p>
<p><%= link_to "Delete #{@product.name}", product_path(@product),
        :data => {:confirm => "Are you sure?", :method => "delete"} %></p>
<p><%= link_to "Return to products", all_products_path %></p>

app/views/reviews/new.html.erb
<h1>Add a review:</h1>

<%= render "layouts/reviews_form" %>